name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Check npm audit
        run: npm run check-audit

      - name: Lint
        run: npm run eslint && npm run lint-md

      - name: Run tests
        run: npm run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Semantic releasing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
